---
title: "30-feature-engineering"
output: html_notebook
---

Right now, we want to calculate the differnce of each parameters. This can help us to see if the changes in rating matches the changes of each countries' happiness score. 

```{r}
Happiness_Rank_Difference<- function(df, y,x){
  df %>% 
  mutate(Happiness_Rank_Difference= {{y}}-{{x}}) 
}
```

```{r}
Happiness_Rank_Difference(df1,happiness_rank.y, happiness_rank.x) %>% 
  select(happiness_rank.y, happiness_rank.x,Happiness_Rank_Difference) %>% 
  assert(within_bounds(lower.bound = -Inf, upper.bound = Inf, allow.na = FALSE), Happiness_Rank_Difference)
```


```{r}
Economics_Difference <-function(df,y,x){
  df %>% 
  mutate(Economics_Difference= {{y}}-{{x}}) 
}
```

```{r}
Economics_Difference(df1, economy_gdp_per_capita.y, economy_gdp_per_capita.x) %>% 
  select(economy_gdp_per_capita.y, economy_gdp_per_capita.x, Economics_Difference) %>% 
  assert(within_bounds(lower.bound = -Inf, upper.bound = Inf, allow.na = FALSE), Economics_Difference)
```


```{r}
Family_Difference <- function(df,y,x){
    df %>% 
    mutate(Family_Difference= {{y}}-{{x}})
}
```

```{r}
Family_Difference(df1,family.y,family.x) %>% 
  select(family.y,family.x,Family_Difference) %>% 
  assert(within_bounds(lower.bound = -Inf, upper.bound = Inf, allow.na = FALSE), Family_Difference)
```


```{r}
Health_Difference <- function(df,y,x){
  df %>% 
  mutate(Health_Difference= {{y}}-{{x}})
}
```

```{r}
Health_Difference(df1,health_life_expectancy.y,health_life_expectancy.x) %>% 
  select(health_life_expectancy.y,health_life_expectancy.x, Health_Difference) %>% 
  assert(within_bounds(lower.bound = -Inf, upper.bound = Inf, allow.na = FALSE), Health_Difference)
```


In the original dataset, we have one colomn called region. I want to create a new feature of continents to better group those countries. 

```{r}
get_continent <- function(df, x){
  
  return_continent <- function(country){ 
  Europe <- c("Norway", "Denmark", "Iceland", "Switzerland", "Finland","Netherlands", "Sweden", "Austria", "Ireland", "Germany","Belgium", "Luxembourg", "United Kingdom", "Czech Republic","Malta", "France", "Spain", "Slovakia", "Poland", "Italy","Russia", "Lithuania", "Latvia", "Moldova", "Romania","Slovenia", "North Cyprus", "Cyprus", "Estonia", "Belarus","Serbia", "Hungary", "Croatia", "Kosovo", "Montenegro","Greece", "Portugal", "Bosnia and Herzegovina", "Macedonia","Bulgaria", "Albania", "Ukraine")
  Australia <- c("New Zealand", "Australia")
  Asia <- c("Israel", "United Arab Emirates", "Singapore", "Thailand", "Taiwan Province of China","Qatar", "Saudi Arabia", "Kuwait", "Bahrain", "Malaysia", "Uzbekistan", "Japan","South Korea", "Turkmenistan", "Kazakhstan", "Turkey", "Hong Kong S.A.R., China", "Philippines","Jordan", "China", "Pakistan", "Indonesia", "Azerbaijan", "Lebanon", "Vietnam","Tajikistan", "Bhutan", "Kyrgyzstan", "Nepal", "Mongolia", "Palestinian Territories","Iran", "Bangladesh", "Myanmar", "Iraq", "Sri Lanka", "Armenia", "India", "Georgia", "Cambodia", "Afghanistan", "Yemen", "Syria")
  North_America <- c("Canada", "Costa Rica", "United States", "Mexico",  
"Panama","Trinidad and Tobago", "El Salvador", "Belize", "Guatemala","Jamaica", "Nicaragua", "Dominican Republic", "Honduras","Haiti")
  South_America <- c("Chile", "Brazil", "Argentina", "Uruguay","Colombia", "Ecuador", "Bolivia", "Peru","Paraguay", "Venezuela")
  Africa <- c("Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon","Chad","Congo (Brazzaville)","Congo (Kinshasa)","Egypt","Ethiopia","Gabon","Ghana","Guinea","Ivory Coast","Kenya","Liberia","Libya","Madagascar","Malawi","Mali","Mauritania","Mauritius","Morocco","Namibia","Niger","Nigeria","Rwanda","Senegal","Sierra Leone","Somalia","South Africa","South Sudan", "Sudan","Tanzania","Togo","Tunisia","Uganda","Zambia","Zimbabwe")

  ctnt <- case_when(country %in% Europe ~ "Europe",
                  country %in% Australia ~ "Australia",
                  country %in% Asia ~ "Asia",
                  country %in% North_America ~ "North_America",
                  country %in% South_America ~ "South_America",
                  country %in% Africa ~ "Africa")
  ctnt
  }
  
  df %>% 
    mutate(continent=return_continent(country))
}
```

```{r}
get_continent(df1, country) %>% 
  select(country, continent) %>% 
  assert(in_set("Europe","Australia","Asia","North_America","South_America","Africa", allow.na = FALSE), continent)

```

```{r}
get_level <- function(df, x, y){

  df %>%
    mutate(happiness_level.x= case_when({{x}} < quantile({{x}}, 0.25)[[1]] ~ "D",
                                      {{x}} >= quantile({{x}}, 0.25)[[1]] & {{x}} < median({{x}}) ~ "C",
                                      {{x}} >= median({{x}}) & {{x}} < quantile({{x}}, 0.75)[[1]] ~ "B",
                                      {{x}} >= quantile({{x}}, 0.75)[[1]] ~ "A"
                             )) %>%
    mutate(happiness_level.x=as.factor(happiness_level.x)) %>%
    mutate(happiness_level.y= case_when({{y}} < quantile({{y}}, 0.25)[[1]] ~ "D",
                                      {{y}} >= quantile({{y}}, 0.25)[[1]] & {{y}} < median({{y}}) ~ "C",
                                      {{y}} >= median({{y}}) & {{y}} < quantile({{y}}, 0.75)[[1]] ~ "B",
                                      {{y}} >= quantile({{y}}, 0.75)[[1]] ~ "A"
                             )) %>%
    mutate(happiness_level.y=as.factor(happiness_level.y))
}
```

```{r}
get_level(df1, happiness_rank.x, happiness_rank.y) %>% 
  select(happiness_rank.x, happiness_level.x, happiness_rank.y, happiness_level.y) %>% 
  assert(in_set("A","B","C","D", allow.na = FALSE), happiness_level.x) %>% 
  assert(in_set("A","B","C","D", allow.na = FALSE), happiness_level.y)
```

```{r}
get_personal_satis <- function(df,a,b,c,d){
  df %>%
    mutate(personal_satis = {{a}}+{{b}}+{{c}}+{{d}})
}
get_social_satis <- function(df,a,b,c){
  df %>%
    mutate(social_satis = {{a}}+{{b}}+{{c}})
}
```

```{r}
get_personal_satis(df1, family.x, health_life_expectancy.x, freedom.x, generosity.x) %>% 
  get_social_satis(economy_gdp_per_capita.x, trust_government_corruption.x, dystopia_residual.x) %>% 
  select(country, personal_satis, social_satis) %>% 
  assert(within_bounds(lower.bound = 0, upper.bound = Inf, allow.na = FALSE), personal_satis) %>% 
  assert(within_bounds(lower.bound = 0, upper.bound = Inf, allow.na = FALSE), social_satis)
```




